### ISSUE TITLE
Pass a full VueX Store Object instead of config?

### ISSUE THREAD

**Issue by Sunhat** [DJanoskova/vuex-but-for-react#1]
Hi Dana - Thanks for the package, the API looks great and easy to use!

I'm hoping to introduce this on my project, but long story short, I've got a VueX Store that I need to plug into React Native AND I'm also using Vue Native.

The Vue Native part can access the VueX Store as normal, has two-way binding, and is completely reactive.

My issue is, when using `withStore(App, config);` and instantiating my own `Vuex.Store(config);` I have two stores! I need to do `Vuex.Store()` for the Vue part of the application, and the goal is to phase out Vue completely.

I need to pass `withStore` the actual `Vuex.Store` or find another solution to this problem, and was wondering if you have any suggestions??

Thanks!

**Comment by DJanoskova** [comment]
Hi @Sunhat, I hope I understand your problem correctly. If I were in your place, I'd probably create a helper function that would return two configs - one for vuex store and one for vuex-but-for-react store. Since you probably want to be keeping all your actions, mutations, getters etc - I would store those in a config file, run them through the helper and generate the syntax for both vuex and vuex-but-for-react configs automatically.
